"""
DocString
Python = Linguagem de programação
Tipo de tipagem = Dinâmica / Forte
str -> string -> texto
"""
#Strings são textos que estão dentro de aspas
print(1234)

# Aspas simples
print('Kyara Amaral')
print(1, 'Kyara "Amaral"')

# Aspas duplas
print("Kyara Amaral")
print(2, "Kyara 'Amaral'")

# Escape \ diz para pular o próximo caractere
print("Kyara \"Amaral\"")

# r
print(r"Kyara \"Amaral\"")
#codigo mais limpo se usar aspas simples dentro de aspas duplas, melhor solução
print("'Kyara Amaral'")
