texto = "programação"
print(texto[0:4])  #vai do indice 0 até 3 pq o zero conta = prog
print(texto[:5])      # 'progr' (do começo até o índice 4)
print(texto[5:])      # 'amação' (do índice 5 até o fim)
print(texto[-3:])     # 'ção' (três últimos caracteres)
print(texto[::-1])    # 'oãçamargorp' (string invertida!)

#agora função LEN
texto = "Python" #PQ PYTHON TEM 6 LETRAS/CARACTERES
print(len(texto)) 
nome = 'kyara'
print(len(nome))