adicao = 10 + 10
print("adição =" , adicao)
subtracao = 10 - 5
print("subtração =" , subtracao)
multiplicacao = 10 * 5
print("multiplicação =", multiplicacao)
divisao = 10 / 5 #para dividir float 
print("Divisão float =" , divisao)
divisao_inteiro = 10 // 5
print('divisão inteiro =' , divisao_inteiro)
exponenciacao = 2 ** 10
print("exponenciaçao =" , exponenciacao)
modulo = 55 % 2 #resto da divisao 
print("módulo =" , modulo)
print(10 % 8 == 0)
print(10 % 2 == 0)
print(16 % 8 == 0)
print(10 % 2 == 0)
print(15 % 2 == 0)
print(16 % 2 == 0)