#input('qual é o seu nome?')
'''nome = input('qual é o seu nome?')
print(f"O seu nome é {nome}")'''

'''
numero_1 = input('Digite um número: ')
numero_2 = input('Digite outro número: ')

int_numero_1 = int(numero_1)
int_numero_2 = int(numero_2)

print(f'A soma dos números é: {int_numero_1 + int_numero_2}')'''
#é necessario converter as variaveis numero e 2 para int se não da erros.
"""outra forma de fazer é ja converter diretamente"""
'''
numero1 = int(input('digite um numero: '))
numero2 = int(input("digite outro numero: "))
soma = numero1 + numero2
print(f"A soma dos numeros é: {soma}")'''

numero1 = int(input('digite um numero: '))
numero2 = int(input("digite outro numero: "))
print(f'A soma dos numeros é: {numero1 + numero2}')

