mensagem = "Estudando python com Kyara"

print(len(mensagem))# Correto ✅ → Mostra o total de caracteres
print(mensagem[10:16])# Correto ✅ → Imprime "python"
print(mensagem[-3:]) # para pegar os ultimos 3 caracteres
print(mensagem[::-1])  # Correto ✅ → Inverte a string inteira
#não esqueça que espaço tbm conta como caracteres

#desafio2
frase = "estudar python é muito divertido e poderoso!"
print(len(frase)) # ✅ CORRETO! Conta todos os caracteres.
print(frase[23:32])  # ✅ CORRETO! imprime divertido na tela 
print(frase[0:5]) # ✅ CORRETO! Pega os 5 primeiros caracteres.
print(frase[-5:]) # ✅ CORRETO! Pega os 5 últimos caracteres.
print(frase[::-1]) # ✅ CORRETO! Frase invertida!